### ISSUE TITLE
traducir measure_distance en cap23

### ISSUE THREAD

**Issue by pachadotdev** [cienciadedatos/r4ds#107]

**Comment by rivaquiroga** [comment]
¿`medida_distancia`?

**Comment by jjgoye** [comment]
sí, puede ser ... no me convence mucho pero tampoco el measure_distance original :-)
Juanjo

**Comment by rivaquiroga** [comment]
Voy a cerrar este issue porque vamos a dejar de hacer modificaciones en la primera edición para comenzar a enfocar los esfuerzos en la segunda.
