### ISSUE TITLE
Error en numeral 3.6. "objetos geométricos"

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/r4ds#121]
Hola, estoy leyendo con atención el libro, y encontré un error en el primer código que se usa de ejemplo en el numeral 3.6. "objetos geométricos". Debería aparecer como:
# izquierda
ggplot(data = millas) +
  geom_point(mapping = aes(x = motor, y = autopista))
# derecha
ggplot(data = millas) +
  geom_smooth(mapping = aes(x = motor, y = autopista))

Muchos saludos y gracias por el empeño.

_Originally posted by @davidbutello in https://github.com/cienciadedatos/documentacion-traduccion-r4ds/issues/1#issuecomment-574330532_

**Comment by rivaquiroga** [comment]
Creo que alguien ya hizo un PR con la corrección
