### ISSUE TITLE
variable categórica vs variable discreta

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/r4ds#123]
Hola

Tengo la siguiente observación que me hizo llegar @rodguez. Mirando el original (https://r4ds.had.co.nz/exploratory-data-analysis.html#cat-cont) creo que a traducir como "variable discreta" y no "variable categórica" se puede generar confusión sobre el hecho que `corte` es de tipo ordinal.

> Mauricio,
> 
> Estuve viendo el libro en el fds y encontré algunas inconsistencias, creo que cuando hablan de variable discreta, realmente se refiere a una categórica en los siguientes puntos.
> 
> Sección 3.
> 
> Esta es una pregunta de los ejercicios de la sección 3 Visualización de datos.
> ![aaa](https://user-images.githubusercontent.com/10091065/75156668-53b99600-56f1-11ea-94d0-c9b987e8fdb6.jpg)
> 
> Y en la sección 7.5.1, claramente debe ser variable categórica y no discreta.
> ![bbb](https://user-images.githubusercontent.com/10091065/75156676-587e4a00-56f1-11ea-8fd3-b551bc0dbb3b.jpg)

**Comment by rivaquiroga** [comment]
De acuerdo!
Lo arreglo durante el fin de semana.
