### ISSUE TITLE
imagen en sección 13.4.1

### ISSUE THREAD

**Issue by jjgoye** [cienciadedatos/r4ds#138]
Compañeros, 
en la sección 13.4.1 aparece la imagen de dos tablas: x e y
En la tabla y la primer columna dice 1, 2, 3 pero debiera decir 1, 2, 4 como en la versión en inglés
Juanjo

![13 4 1-](https://user-images.githubusercontent.com/34039013/93829885-15fbfc00-fc45-11ea-96fb-34cbd2e49a33.png)

**Comment by rivaquiroga** [comment]
Voy a cerrar este issue porque vamos a dejar de hacer modificaciones en la primera edición para comenzar a enfocar los esfuerzos en la segunda. Si el contenido sigue existiendo en la segunda edición, lo arreglamos ahí
