### ISSUE TITLE
Sección 5.2.2 Operadores lógicos figura 5.1

### ISSUE THREAD

**Issue by luifrancgom** [cienciadedatos/r4ds#140]
En la sección 5.2.2 Operadores lógicos en el primer párrafo es necesario corregir la referencia @ref(fig:bool-ops)  incluyendo "\\"
para que el usuario final pueda visualizar "5.1"

También el subtítulo de la figura 5.1 esta en inglés por lo que se requiere traducir el texto en la opción fig.cap del rmarkdown dado que aparece:  "Complete set of boolean operations. `x` is the left-hand circle, `y` is the right-hand circle, and the shaded region show which parts each operator selects."

Podría inlcuirse como: "Conjunto completo de operaciones booleanas. `x` corresponde al círculo de la izquierda, `y` corresponde al círculo de la derecha, y la región sombreada señala qué partes selecciona cada operador."

**Comment by rivaquiroga** [comment]
¡Hola, @luifrancgom! Hay un pull request abierto en el que incoporamos este cambio: https://github.com/cienciadedatos/r4ds/pull/139
En estos momentos hay algunos problemas con el build del libro, así que todavía no se actualiza esa modificación. Esperamos poder resolverlos en los próximos días

**Comment by luifrancgom** [comment]
A listo muchas gracias. La pŕoxima vez reviso bien los cambios que se encuetran ya propuestos.
