### ISSUE TITLE
5.4.1 Ejercicios numeral 3 cambiar one_of() por any_of()

### ISSUE THREAD

**Issue by luifrancgom** [cienciadedatos/r4ds#141]
`one_of` fue reemplazado por `any_of` o `all_of` en el paquete `tidyselect` version 1.0.0 y en la versión 1.0.1 se corrigió un problema de la función `any_of` en base a lo señalado en https://tidyselect.r-lib.org/news/index.html. 

En base a lo anterior en el libro en inglés dentro de la sección 5.4.1 Exercises numeral 3 `one_of()` se cambió de forma definitiva por `any_of()` donde se podría agregar este cambio a la versión en español.

**Comment by rivaquiroga** [comment]
¡Hola, @luifrancgom! Muchas gracias por la sugerencia. Si quieres puedes hacer un _pull request_ con la propuesta de modificación para que quede registrada tu colaboración en el libro. Avísanos si te interesa, si no, para hacer nosotros el cambio

**Comment by luifrancgom** [comment]
Cordia saludo

Si desean lo pueden hacer ustedes es un cambio bastante pequeño. La próxima vez acumularé más acumularé más cambios para que un pull request valga la pena.

**Comment by rivaquiroga** [comment]
@luifrancgom, todos los pull request valen la pena. Aunque sea para cambiar un punto o una coma. Todos los aportes son bienvenidos :nerd_face:
