### ISSUE TITLE
Sección 11.3.5 Ejercicios numeral 7

### ISSUE THREAD

**Issue by luifrancgom** [cienciadedatos/r4ds#144]
Cordial saludo 

En la sección 11.3.5 Ejercicios numeral 7 respecto a:

`d4 <- c("Augosto 19 (2015)", "Julio 1 (2015)")`

El ejercicio tal como está es interesante pero no sé si se construyó a propósito. 

Creo que es un typo dado que no creo que sea A**u**gosto sino Agosto. 

De lo contrario la solución del ejercicio sería:

```
library(tidyverse)

parse_date(d4, 
           format = "%B %d (%Y)", 
           locale = locale(date_names = date_names(mon = c("enero", "febrero", "marzo", "abril", "mayo", "junio", 
                                                           "julio", "augosto", "septiembre", "octubre", "noviembre", 
                                                           "diciembre"),
                                                   day = c("domingo", "lunes", "martes", "miércoles", "jueves",
                                                           "viernes", "sábado")))) 
```

Creando un locale personalizado con `augosto`

**Comment by rivaquiroga** [comment]
Gracias! Es un typo. Lo corregiremos en los próximos días.

**Comment by rivaquiroga** [comment]
Voy a cerrar este issue porque vamos a dejar de hacer modificaciones en la primera edición para comenzar a enfocar los esfuerzos en la segunda. Si el contenido sigue existiendo en la segunda edición, lo arreglaremos ahí
