### ISSUE TITLE
 13.2 Datos sobre vuelos variable codigo_carrier no definida en datos

### ISSUE THREAD

**Issue by luifrancgom** [cienciadedatos/r4ds#145]
Cordial saludo 

En la sección  13.2 Datos sobre vuelos se indica que:

"`vuelos` se conecta con `aerolineas` a través de la variable `codigo_carrier`."

Sin embargo la variable `codigo_carrier` no existe en `vuelos` o `aerolineas`. 

Supongo que lo correcto sería:

"`vuelos` se conecta con `aerolineas` a través de la variable `aerolínea`."

**Comment by rivaquiroga** [comment]
¡Hola! Voy a cerrar este issue porque vamos a dejar de hacer modificaciones en la primera edición para comenzar a enfocar los esfuerzos en la segunda. Cuando lleguemos al capítulo 13 haremos la actualización si sigue siendo necesario
