### ISSUE TITLE
Título html en bienvenida

### ISSUE THREAD

**Issue by jbkunst** [cienciadedatos/r4ds#148]
Hola!

En la página inicial de https://es.r4ds.hadley.nz/ la etiqueta en el explorador google se ve de la siguiente manera:

![image](https://user-images.githubusercontent.com/56481/116490424-5966ba80-a865-11eb-9822-b640f8a24302.png)

Al ver el código fuente se observa `<title>Bienvenida | _main.utf8</title>`  en la línea 7:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bienvenida | _main.utf8</title>
<!-- JS -->
````

**Comment by rivaquiroga** [comment]
Ahora que me fijo, pasa en todas las páginas :grimacing: 
Habrá qué explorar para ver qué está pasando

**Comment by pachadotdev** [comment]
lo veo recién
tiene que ver con el cambio al tema nuevo de bookdown

**Comment by rivaquiroga** [comment]
Esto ya está resuelto, así que cerraré este issue
