### ISSUE TITLE
Omnigraffle licenses?

### ISSUE THREAD

**Issue by hadley** [cienciadedatos/r4ds#15]
I'd be happy to sponsor a couple of omnigraffle licenses to help translate the diagrams.

**Comment by pachamaltese** [comment]
amazing! thanks a lot @hadley 
shall I email you so I translate these?

**Comment by rivaquiroga** [comment]
I'm pinging @edgararuiz, as he was is in charge of the diagrams translation

**Comment by pachamaltese** [comment]
thanks @rivaquiroga, I'll focus on CI then

**Comment by edgararuiz** [comment]
@pachamaltese - I don't mind moving some of our responsibilities around if you'd like to work on the diagrams.  We can discuss on Slack if you like.

**Comment by hadley** [comment]
Sorry, I meant to imply that I would purchase omnigraffle for anyone who needed it. I don't think my translations would be very good given that I don't speak Spanish 😄

**Comment by pachamaltese** [comment]
Hi @hadley. That's clear! @edgararuiz meant switching some tasks with me, I sent him an email that shall go to your inbox.

**Comment by pachamaltese** [comment]
@hadley all the diagrams were redrawn by using inkscape which is open, multi platform and svg compatible
this eases translation to even more languages
here's the link https://github.com/pachamaltese/r4ds/tree/traduccion/diagrams
