### ISSUE TITLE
Capítulo 21, Sección 21.5.2 R Base  hay una duplicación de la palabra "es"

### ISSUE THREAD

**Issue by monialo2000** [cienciadedatos/r4ds#151]
Hola gente! Al explicar vapply() hay un error de tipeo. figura dos veces **es**
 "El único problema con vapply() es es que requiere mucha escritura:"

**Comment by rivaquiroga** [comment]
Voy a cerrar este issue porque vamos a dejar de hacer modificaciones en la primera edición para comenzar a enfocar los esfuerzos en la segunda edición.
