### ISSUE TITLE
enlace a capítulo 6 en cap. 2 (Introducción) con formato incorrecto

### ISSUE THREAD

**Issue by FelipeLema** [cienciadedatos/r4ds#152]
Hola, qué tal

En el capítulo 2 "Introducción", en el último párrafo se hace referencia a los capítulos "flujo de trabajo: conocimientros básicos" (cap. 4), "flujo de trabajo: Scripts" (cap. 6) & "flujo de trabajo: proyectos" (cap. 8). Los enlaces a capítulos 4 & 8 están correctamente formateados, pero no así el enlace al capítulo 6

**Comment by rivaquiroga** [comment]
¡Hola, Felipe! 
Muchas gracias por avisarnos. En los próximos días lo modificaremos. 
¡Saludos!

**Comment by rivaquiroga** [comment]
Voy a cerrar este issue porque vamos a dejar de hacer modificaciones en la primera edición para comenzar a enfocar los esfuerzos en la segunda.
