### ISSUE TITLE
Traducción de Tutoriales en paquete learnr?

### ISSUE THREAD

**Issue by xavidp** [cienciadedatos/r4ds#156]
Hola:

Trabajo para una administración pública relacionada con la educación local (antes trabajaba en data science con R en bioinformática), y estaba buscando recursos para montar un curso de R moderno (tidyverse-et-al) para funcionarios/as que quizás no dominen inglés. He visto que el paquete learnr trae tutoriales (en inglés) que estan vinculados con capítulos del libro (en inglés) de r4ds (v1).

Y me preguntaba cual seria la forma más adecuada de poder traducir los tutoriales del paquete learnr ( al menos los primeros 5 listados aquí: https://github.com/rstudio/learnr/tree/main/inst/tutorials ) de forma que pueden enlazarse con los capítulos correspondientes de la traducción que habéis hecho vosotros/as del r4ds (v1)

¿Cual seria la mejor forma de proceder?

Gracias por adelantado, y disculpad por la sensación de newbie total que tengo ahora mismo enviandoos este mensaje (se que esto no es un issue propiamente dicho de cienciadedatos/r4ds pero no sé de qué otra forma enviar esta pregunta/propuesta).

Xavier de Pedro , Ph.D. (usuario de R desde hace más de 15 años)

**Comment by pachadotdev** [comment]
hola @xavidp 
no creo que esto sea newbie
yo mirar'ia el paquete datos, el cual se hace cargo de las traducciones de los datasets (https://github.com/cienciadedatos/datos) y luego ver'ia https://github.com/cienciadedatos/documentacion-traduccion-r4ds#materiales-de-trabajo

**Comment by xavidp** [comment]
hola @pachadotdev , gracias por tus indicaciones.

He enviado un pull request ( https://github.com/cienciadedatos/r4ds/pull/158 ) con una prueba de concepto de como se podría gestionar el tema de las traducciones estas. A ver qué os parece.

Ya me diréis si interesa seguir este camino, u otro (o no interesa poner a disposición de otras personas estos tutoriales traducidos a través del espacio de "cienciadedatos").

Saludos
