### ISSUE TITLE
Automatically build book into website

### ISSUE THREAD

**Issue by hadley** [cienciadedatos/r4ds#16]
I think it makes it easier to keep up motivation when you can see the results online.

The easiest way these days is netlify, and you can see the travis code for adv-r at https://github.com/hadley/adv-r/blob/master/.travis.yml#L16-L22

Let me know if you'd like help getting the other pieces set up, or want a domain name like `es.r4ds.hadley.nz`

**Comment by pachamaltese** [comment]
Hi @hadley if you can provide es.r4ds.hadley.nz that would be awesome!
I'll ping back when I have netlify ready

**Comment by rivaquiroga** [comment]
Thanks @hadley! 
We are going to present the translation project at LatinR, so it would be great if we can show the progress in an 'official' domain.

**Comment by hadley** [comment]
Sure, just let me know when you have netlify set up, and I'll connect the domain from my end.

**Comment by pachamaltese** [comment]
@hadley I used gh-pages and travis: https://cienciadedatos.github.io/r4ds/
netlify gave some problems with á é í ó ú that are used in spanish
so, we would just need to add es.r4ds.hadley.nz to CNAME and point it in the domain settings

**Comment by hadley** [comment]
I just set up a CNAME from `http://es.r4ds.hadley.nz` to `cienciadedatos.github.io` so you should be able to set the CNAME in the github admin, and should work in an hour or two.

**Comment by hadley** [comment]
BTW it's es.r4ds.hadley.nz not es.r4ds.had.co.nz

**Comment by pachamaltese** [comment]
fixed
