### ISSUE TITLE
posible frase incorrecta

### ISSUE THREAD

**Issue by pachadotdev** [cienciadedatos/r4ds#164]
Hola @rivaquiroga 

Acá en el ejercicio 1 en 3.3.1 (https://cienciadedatos.github.io/r4ds/03-visualize.html#mapeos-est%C3%A9ticos) dice "qué no va bien". ¿Es correcto eso o debe decir "qué no está bien"?

Se puede modificar directo en github y el html se va a actualizar.

**Comment by rivaquiroga** [comment]
¡Hola!
Arreglémoslo en la segunda edición. 
Pero mirando esa parte vi que pasa esto:

![Captura de pantalla 2023-08-09 a la(s) 18 19 39](https://github.com/cienciadedatos/r4ds/assets/31421616/58ab2f9f-109d-429a-9fdb-b7b987ec05f0)
