### ISSUE TITLE
Error: Sitio no seguro

### ISSUE THREAD

**Issue by TuQmano** [cienciadedatos/r4ds#166]
## Problema con certificados para conexión segura https://es.r4ds.hadley.nz/factores.html

![image](https://github.com/cienciadedatos/r4ds/assets/12114624/952212a8-2185-4bd7-af0b-006e6aa7c1c7)

![image](https://github.com/cienciadedatos/r4ds/assets/12114624/a06b7ecc-3c0d-4fb0-8528-47e04d071bcf)

**Comment by pachadotdev** [comment]
hola @TuQmano 
ya le avisamos de eso a Hadley hace unas semanas
voy a ver si puedo regenerar el certificado desde aca

**Comment by pachadotdev** [comment]
listo @TuQmano 
ya le pedi agregar un TXT

**Comment by pachadotdev** [comment]
@TuQmano ya esta ok, muchas gracias a @hadley a quien tuve que molestar y pedirle que haga cambios en su dominio

deberias poder ver la version "nueva" (nuevo render, con Quarto), pronto tendremos la 2da edicion

![Screenshot_20230809_165920](https://github.com/cienciadedatos/r4ds/assets/10091065/51a45977-2ed4-422d-96be-c669ee1a52be)

**Comment by TuQmano** [comment]
Excelente! Grax x el laburo!

**Comment by hadley** [comment]
Woohoo! 🥳
