### ISSUE TITLE
Translate welcome page

### ISSUE THREAD

**Issue by hadley** [cienciadedatos/r4ds#18]
I think you should mention prominently that it's a translation, and link back to the original website, and to amazon (that will make O'Reilly happy).

You should also update the yaml meta data so the edit link comes to this repo, and so that you all are listed as authors.

**Comment by pachamaltese** [comment]
@hadley ready!

**Comment by hadley** [comment]
Looks great!

**Comment by rivaquiroga** [comment]
Hadley, one question: 
It's ok if we put in the welcome page the "About the translation" section? Below everything. It's one paragraph that explain briefly the collaborative nature of the project. I can send you an english version if you want to check it first.

**Comment by pachamaltese** [comment]
@hadley: @rivaquiroga has a huge point :arrow_up:

**Comment by hadley** [comment]
Yes, definitely! And maybe move the book cover image to a new section "About the English version"? (You could also make the book cover smaller). This would also be a nice place to public thank the contributors to the translation, and include your lovely hex logo.

**Comment by rivaquiroga** [comment]
The first version of the welcome page is ready :rocket: 
It explains the collaborative nature of the project, thanks the contributors, clarifies that the translation is in progress, and tells people how to participate.

**Comment by hadley** [comment]
Now that you have a website and welcome page, is it ok for me to tweet about it?

**Comment by rivaquiroga** [comment]
Sure! That will be great :nerd_face:

**Comment by hadley** [comment]
Do you have a collection of all your twitter handles handy?

**Comment by rivaquiroga** [comment]
Give me a couple of minutes, and I'll generate it

**Comment by rivaquiroga** [comment]
Sorry for delay. Here it is, in alfabetical order:

@Fichulina
@MonicaLA2000 ‏
@fdo_alvarez_S ‏
@yabellini
@July_Benitezs
@d_olivaw
@cantoflor_87
@jbkunst
@patriloto 
@pamelinni
@PaoPrieto
@rivaquiroga
@_luciarp_
@theotheredgar
@pachamaltese 
@d4tagirl
@data_datum

**Comment by rivaquiroga** [comment]
Thanks @hadley!  :)
