### ISSUE TITLE
update the cover image

### ISSUE THREAD

**Issue by raynamharris** [cienciadedatos/r4ds#50]
I'm not sure if O'Riley is going to print this book or not. This is one option for an updated cover, generated using https://dev.to/rly

![cover-es](https://user-images.githubusercontent.com/7544197/51432064-3a454100-1bf7-11e9-8df8-9eeb1511e8a7.png)

**Comment by rivaquiroga** [comment]
O'Reilly is not going to translate it. That is why we are doing it. As this is an independent project, maybe is better to no use an O'Reilly-style image.

**Comment by pachamaltese** [comment]
Thanks Riva! Let me suggest a cover later

**Comment by raynamharris** [comment]
Good point. Maybe it can be made using the hex image that is the profile of https://github.com/cienciadedatos

**Comment by rivaquiroga** [comment]
I don’t think is necessary. We are using the hex logo as cover image and project image. Having to official images could be confusing.
By the way, the old version is the one currently displayed. I’ll change it right now.
