### ISSUE TITLE
problemas con capítulos "RMarkdown" y "RMarkdown workflow"

### ISSUE THREAD

**Issue by rivaquiroga** [cienciadedatos/r4ds#76]
¡Hola!
Hay dos asuntos que revisar en el PR #41  de @julybenitez:

__1. Capítulo "R Markdown".__ Al hacer la traducción no se borraron los párrafos de la versión en inglés, por lo que actualmente está intercalada la versión original y la versión en español: https://es.r4ds.hadley.nz/r-markdown.html. 

__2. Capítulo "R Markdown workflow".__ Ocurre lo mismo: están los párrafos intercalados entre ambos idiomas: https://es.r4ds.hadley.nz/flujo-de-trabajo-en-r-markdown.html. Además, como pareciera que la traducción se hizo en una copia del archivo, quedó esta sección en blanco que habría que eliminar: https://es.r4ds.hadley.nz/r-markdown-workflow.html

En definitiva, habría que borrar los párrafos en inglés y eliminar la sección duplicada. @julybenitez, avísanos si podrías resolver esto. 

¡Muchas gracias!

**Comment by pachamaltese** [comment]
Lo puedo resolver acá con un diff

**Comment by rivaquiroga** [comment]
¡Gracias!

**Comment by pachamaltese** [comment]
Ayer quedó listo con un merge bien importante
