### ISSUE TITLE
paleta en visualize.Rmd

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/r4ds#77]
output file: visualize.knit.md

Warning messages:
1: Using alpha for a discrete variable is not advised. 
2: The shape palette can deal with a maximum of 6 discrete values
because more than 6 becomes difficult to discriminate; you have 7.
Consider specifying shapes manually if you must have them. 
3: Removed 62 rows containing missing values (geom_point).

**Comment by rivaquiroga** [comment]
En el original también aparecen esos warnings: https://travis-ci.org/github/hadley/r4ds

El primero es de acá:

```
ggplot(data = millas) +
  geom_point(mapping = aes(x = cilindrada, y = autopista, size = clase))
#> Warning: Using size for a discrete variable is not advised.
```

Los otros dos son de este bloque que tiene los `warnings = FALSE`

```{r out.width = "50%", fig.align = 'default', warning = FALSE, fig.asp = 1/2, fig.cap =""}
# Izquierda
ggplot(data = millas) +
  geom_point(mapping = aes(x = cilindrada, y = autopista, alpha = clase))
# Derecha
ggplot(data = millas) +warnings = FALSE
  geom_point(mapping = aes(x = cilindrada, y = autopista, shape = clase))
```
