### ISSUE TITLE
Error in figure in spanish translation

### ISSUE THREAD

**Issue by glpuga** [cienciadedatos/r4ds#88]
There's an error in [this figure](https://github.com/cienciadedatos/r4ds/blob/traduccion/diagrams_w_text_as_path/es/transform-logical.svg) used in the Spanish translation of the book  and visible [in section 5.2.2 here](https://es.r4ds.hadley.nz/transform.html).

The diagram for `x & !y` case (lower left) should not paint the region shared by `x` and `y`.

**Comment by pachamaltese** [comment]
fixed in https://github.com/cienciadedatos/r4ds/pull/89
