### ISSUE TITLE
textos en inglés capítulo 19

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/r4ds#96]
puede que haya más

https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L168
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L262
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L297
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L324
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L341
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L355
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L382
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L389
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L486
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L536

**Comment by pachamaltese** [comment]
propuesta de solución:
https://github.com/pachamaltese/r4ds/commit/48d313ff0c5eba417f48d4867583ced0389d0586

**Comment by rivaquiroga** [comment]
Resuelto!
