### ISSUE TITLE
género neutral en capítulo 19

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/r4ds#97]
debería decir "cientista"
https://github.com/cienciadedatos/r4ds/blob/traduccion/19-functions.Rmd#L5

**Comment by pachamaltese** [comment]
propuesta de solución:
https://github.com/pachamaltese/r4ds/commit/a51739f05832ef904cf8edf54a8df653160a3301

**Comment by rivaquiroga** [comment]
Reformular la oración para evitar tener que utilizar adjetivos con género femenino/masculino se había planteado como una opción en los lineamientos de la traducción. La reformulación parece una mejor solución en este caso para saltarnos la discusión sobre si es "cientista de datos" o "científico/ca de datos".
