### ISSUE TITLE
textos en inglés capítulo 20

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/r4ds#98]
https://github.com/cienciadedatos/r4ds/blob/traduccion/20-vectors.Rmd#L19

**Comment by pachamaltese** [comment]
propuesta de corrección: https://github.com/pachamaltese/r4ds/commit/6b627a13b6f9b4637f88eb9ca64564e55600f174

**Comment by rivaquiroga** [comment]
Resuelto!
