### ISSUE TITLE
Error en path a diagrams 01-intro.Rmd 

### ISSUE THREAD

**Issue by pabecer** [cienciadedatos/r4ds#99]
Estimados, 
Los diagramas en la introducción están direccionados a diagrams/ y no a diagrams/es/, por lo que  no se muestran en https://es.r4ds.hadley.nz/introduccion.html
Son 2 diagramas en las lineas 10 y 117 del código.

**Comment by pachamaltese** [comment]
Hola
Eso ya está cambiado en un PR que hice ayer

**Comment by pachamaltese** [comment]
solución: https://github.com/cienciadedatos/r4ds/pull/100
